vich_uploader:
    db_driver: orm

    mappings:
        painting_image:
            uri_prefix: /assets/images/paintings
            upload_destination : '%kernel.project_dir%/public/assets/images/paintings'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        media_image:
            uri_prefix: /assets/images/medias
            upload_destination: '%kernel.project_dir%/public/assets/images/medias'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        style_image:
            uri_prefix: /assets/images/styles
            upload_destination: '%kernel.project_dir%/public/assets/images/styles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        artist_image:
            uri_prefix: /assets/images/artists
            upload_destination: '%kernel.project_dir%/public/assets/images/artists'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
